### ISSUE TITLE
Node and Grunt

### ISSUE THREAD

**Issue by skymaiden** [anthonygrignoux/cocktail-screwdriver#1]
I think it would be a good idea to document what version of Node is required, and that Grunt CLI needs to be installed globally (`npm install -g grunt-cli`) – or maybe have the Grunt CLI in package.json to install it locally...

**Comment by anthonygrignoux** [comment]
Requirements added in:  
https://github.com/anthonygrignoux/cocktail-screwdriver/commit/9581de65c1b81db7a1397840034019429cf60dcd
